// ===== The Last Login: 게임 데이터 =====

const VICTIM = {
  name: '한도경',
  nickMain: '코스모스84', // 메인 채팅방 닉네임
  nickAlt: '달빛유령', // 인디게임 커뮤니티 닉네임
};

const SUSPECTS = {
  A: { id: 'A', name: '서지안', nick: '라플레시아', blurb: '실종자와 가장 친했던 사람' },
  B: { id: 'B', name: '표민준', nick: '밤안개', blurb: '사건 당일 실종자와 다툼' },
  C: { id: 'C', name: '윤소하', nick: '필름누아르', blurb: '사진·영상 촬영을 좋아함' },
  D: { id: 'D', name: '강태오', nick: '그림자탐정', blurb: '검색을 매우 많이 하는 사람' },
  E: { id: 'E', name: '임하율', nick: '겨울정원', blurb: '현실에선 안 만났다 주장' },
  F: { id: 'F', name: '백준경', nick: '고요', blurb: '존재감이 거의 없는 사람' },
};

// 채팅방: 실종 전날 밤 로그 (플레이어가 읽는 결정적 배경 정보 + 나중에 재해석되는 대사 포함)
const CHATLOG_SEED = [
  { from: 'other', name: '라플레시아', text: '오늘 미궁의 늪 접속할 사람?' },
  { from: 'other', name: '코스모스84', text: '나 있음. 새벽까지 할 듯 ㅋㅋ' },
  { from: 'other', name: '밤안개', text: '또 밤샘이야? 낼 모임인데' },
  { from: 'other', name: '코스모스84', text: '모임 전에 끝낼 거임 걱정마' },
  { from: 'other', name: '필름누아르', text: '내일 다락방에서 사진 많이 찍을 거니까 다들 늦지 말기' },
  { from: 'other', name: '그림자탐정', text: '(딴 얘기) 근데 온새미로 골목 그거 뭐임? 옛날 사진관 자리라던데' },
  { from: 'other', name: '고요', text: '아 그 골목 얘기 아직도 하네' },
  { from: 'other', name: '겨울정원', text: 'ㅋㅋㅋ 옛날 얘기지 뭐' },
  { from: 'other', name: '밤안개', text: '아무튼 낼 보자' },
  { from: 'other', name: '코스모스84', text: '어 낼 봐. 나 할 말도 있고' },
  { from: 'other', name: '고요', text: '...무슨 얘기?' },
  { from: 'other', name: '코스모스84', text: '만나서 얘기할게' },
];

// ===== 50개 단서 =====
// requires: 이 단서를 발견하기 위해 미리 발견해야 하는 단서 id 목록 (전부 만족해야 함). 비어있으면 처음부터 검색 가능.
// keywords: 이 검색어(부분일치, 대소문자 무시)를 입력하면 매칭됨.
// reveals: 발견 시 플레이어에게 새로 안내되는 키워드(수첩에 표시).
const CLUES = [
  { id: 1, chain: 'A', suspect: null, tag: 'connector',
    keywords: ['코스모스84'], requires: [],
    title: '익명 커뮤니티 계정 - 코스모스84',
    body: '실종자 한도경이 익명 커뮤니티에서 쓰던 계정. 일상적인 잡담과 게임 이야기가 대부분이다.',
    reveals: ['달빛유령'] },
  { id: 2, chain: 'A', suspect: null, tag: 'connector',
    keywords: ['달빛유령'], requires: [1],
    title: '인디게임 갤러리 - 달빛유령',
    body: '전혀 다른 커뮤니티지만 말투와 어투가 코스모스84와 거의 동일하다. 같은 사람으로 보인다.',
    reveals: ['미궁의 늪'] },
  { id: 3, chain: 'A', suspect: null, tag: 'connector',
    keywords: ['미궁의 늪', '달빛유령 미궁의 늪'], requires: [2],
    title: '게임 플레이 기록 - 미궁의 늪',
    body: '실종 전날, 달빛유령 계정으로 "미궁의 늪"을 플레이한 기록이 있다.',
    reveals: ['플레이 시간'] },
  { id: 4, chain: 'A', suspect: null, tag: 'connector',
    keywords: ['플레이 시간'], requires: [3],
    title: '플레이 로그',
    body: '실종 당일 새벽까지 접속해 있었다. 혼자가 아니라 파티 플레이였다.',
    reveals: ['같이 플레이한 사람'] },
  { id: 5, chain: 'A', suspect: 'A', tag: 'lead',
    keywords: ['같이 플레이한 사람'], requires: [4],
    title: '파티 멤버',
    body: '같이 플레이한 파티원의 닉네임은 "라플레시아". 채팅방 멤버 서지안의 닉네임과 같다.',
    reveals: ['라플레시아'] },

  { id: 6, chain: 'B', suspect: 'A', tag: 'lead',
    keywords: ['라플레시아'], requires: [5],
    title: '다른 사이트의 라플레시아',
    body: '취미 커뮤니티에서도 동일한 닉네임을 사용 중. 최근 글에 "다락방"이라는 장소가 반복적으로 언급된다.',
    reveals: ['다락방'] },
  { id: 7, chain: 'B', suspect: 'A', tag: 'support',
    keywords: ['다락방 라플레시아'], requires: [6],
    title: '단골 인증 글',
    body: '서지안이 "다락방"이라는 보드게임 카페의 단골이라는 게시글. 자주 방문한 흔적이 많다.',
    reveals: [] },
  { id: 8, chain: 'B', suspect: null, tag: 'connector',
    keywords: ['코스모스84 다락방'], requires: [6],
    title: '실종자의 검색 기록',
    body: '한도경도 "다락방"을 여러 번 검색한 기록이 있다. 단순한 우연은 아닌 듯하다.',
    reveals: [] },
  { id: 9, chain: 'B', suspect: null, tag: 'connector',
    keywords: ['다락방 날짜', '다락방 실종일'], requires: [7, 8],
    title: '그날의 다락방',
    body: '실종 당일, 다락방에서는 "미궁의 늪 오프라인 정기모임"이 열렸다.',
    reveals: ['오프라인 정기모임'] },
  { id: 10, chain: 'B', suspect: null, tag: 'connector',
    keywords: ['오프라인 정기모임 코스모스84', '오프라인 정기모임 사진'], requires: [9],
    title: '모임 후기 게시글',
    body: '모임 후기 게시글 속 사진에 한도경이 찍혀 있다. 실종 당일 그 자리에 있었다는 뜻이다.',
    reveals: ['행사 사진'] },

  { id: 11, chain: 'C', suspect: null, tag: 'connector',
    keywords: ['행사 사진', '코스모스84 사진'], requires: [10],
    title: '단체사진',
    body: '한도경과 다섯 명의 채팅방 멤버가 함께 찍힌 단체사진이 발견된다.',
    reveals: ['사진 배경'] },
  { id: 12, chain: 'C', suspect: null, tag: 'connector',
    keywords: ['사진 배경', '사진 확대'], requires: [11],
    title: '사진 확대',
    body: '배경에 흐릿하게 오래된 간판이 보인다. "온새미로"라고 적혀 있는 것 같다.',
    reveals: ['온새미로'] },
  { id: 13, chain: 'C', suspect: null, tag: 'support',
    keywords: ['온새미로'], requires: [12],
    title: '지도 검색 결과',
    body: '"온새미로"는 다락방 카페가 들어서기 전 그 자리에 있던 오래된 사진관 이름이다.',
    reveals: [] },
  { id: 14, chain: 'C', suspect: null, tag: 'support',
    keywords: ['온새미로 후기', '다락방 후기'], requires: [13],
    title: '방문 후기',
    body: '"다락방" 카페에 대한 방문 후기 글. 작성자가 사진을 유독 많이 찍어 올렸다.',
    reveals: ['후기 작성자'] },
  { id: 15, chain: 'C', suspect: 'C', tag: 'lead',
    keywords: ['후기 작성자'], requires: [14],
    title: '작성자 프로필',
    body: '후기 작성자의 닉네임은 "필름누아르". 채팅방 멤버 윤소하의 닉네임이다.',
    reveals: ['필름누아르'] },
  { id: 16, chain: 'C', suspect: 'C', tag: 'lead',
    keywords: ['필름누아르 사진'], requires: [15],
    title: '사진 편집 취미',
    body: '필름누아르는 사진을 자주 편집해서 올리는 것으로 유명하다.',
    reveals: ['사진 파일 정보'] },
  { id: 17, chain: 'C', suspect: 'C', tag: 'support',
    keywords: ['사진 파일 정보'], requires: [16],
    title: '파일 속성',
    body: '문제의 단체사진 파일 속성을 확인해보니 수정 시간이 촬영 시간보다 한참 뒤다.',
    reveals: ['IMG_0603_final'] },
  { id: 18, chain: 'C', suspect: null, tag: 'connector',
    keywords: ['img_0603_final', 'IMG_0603_final'], requires: [17],
    title: '원본으로 보이는 파일',
    body: '동일한 이름의 원본 파일이 다른 게시판 캐시에 남아있다.',
    reveals: ['원본 사진 비교'] },
  { id: 19, chain: 'C', suspect: null, tag: 'lead',
    keywords: ['원본 사진 비교'], requires: [18],
    title: '원본과 비교',
    body: '원본 사진에는 분명히 한도경이 있다. 그런데 지금 돌아다니는 사진에는 없다.',
    reveals: ['이미지 편집 흔적'] },
  { id: 20, chain: 'C', suspect: null, tag: 'lead',
    keywords: ['이미지 편집 흔적'], requires: [19],
    title: '편집 흔적',
    body: '사진 파일에 이미지 편집 프로그램을 사용한 메타데이터 흔적이 남아있다. 누군가 의도적으로 한도경을 지운 것이다.',
    reveals: ['포토샵 질문'] },

  { id: 21, chain: 'PS', suspect: 'C', tag: 'redherring',
    keywords: ['필름누아르 포토샵'], requires: [20],
    title: '이미지 편집 커뮤니티',
    body: '필름누아르가 이미지 편집 커뮤니티에서 꽤 오래 활동해온 것으로 확인된다.',
    reveals: [] },
  { id: 22, chain: 'PS', suspect: 'C', tag: 'redherring',
    keywords: ['필름누아르 사진 편집', '사진에서 사람 지우는 법'], requires: [21],
    title: '질문 게시글',
    body: '"사진에서 특정 인물만 자연스럽게 지우는 방법"을 질문하는 게시글을 필름누아르가 작성했다.',
    reveals: [] },
  { id: 23, chain: 'PS', suspect: 'C', tag: 'redherring',
    keywords: ['질문 게시글 날짜'], requires: [22],
    title: '게시글 작성일',
    body: '게시글 작성일은 한도경이 실종되기 바로 전날이다. 소름 끼치는 타이밍이다.',
    reveals: [] },
  { id: 24, chain: 'PS', suspect: null, tag: 'connector',
    keywords: ['질문 게시글 댓글'], requires: [23],
    title: '댓글',
    body: '댓글 중 하나가 구체적인 복원/삭제 방법과 함께 "이 방법이면 감쪽같음"이라고 답한다.',
    reveals: ['복원 방법'] },
  { id: 25, chain: 'PS', suspect: null, tag: 'lead',
    keywords: ['복원 방법', 'img_0603_final 재검색'], requires: [24],
    title: '방법의 재발견',
    body: '이 방법은 필름누아르뿐 아니라 이 글을 읽은 누구나 따라할 수 있었다. 즉, 사진을 실제로 조작한 사람이 꼭 필름누아르라는 보장은 없다.',
    reveals: ['온새미로 실종'] },

  { id: 26, chain: 'PAST', suspect: null, tag: 'connector',
    keywords: ['온새미로 실종'], requires: [],
    title: '10년 전 기사',
    body: '10년 전, 온새미로 사진관 인근 골목에서 여고생이 실종된 사건 기사를 발견한다. 피해자 이름은 백가영.',
    reveals: ['백가영'] },
  { id: 27, chain: 'PAST', suspect: 'F', tag: 'lead',
    keywords: ['백가영'], requires: [26],
    title: '백가영의 가족관계',
    body: '백가영에게는 당시 어린 사촌 동생이 하나 있었다. 이름은 백준경.',
    reveals: [] },
  { id: 28, chain: 'PAST', suspect: 'F', tag: 'lead',
    keywords: ['백가영 사촌', '백준경 백가영'], requires: [27],
    title: '연결고리',
    body: '지금 채팅방의 "고요" 백준경이 바로 그 사촌 동생이다.',
    reveals: [] },
  { id: 29, chain: 'PAST', suspect: null, tag: 'support',
    keywords: ['백가영 사진'], requires: [27],
    title: '과거 사진',
    body: '백가영 실종 당시 기사에 실린 배경 사진이 지금의 "온새미로" 골목과 정확히 일치한다.',
    reveals: [] },
  { id: 30, chain: 'PAST', suspect: 'F', tag: 'support',
    keywords: ['백가영 실종 댓글'], requires: [29],
    title: '기사 댓글',
    body: '당시 기사 댓글 중 하나가 유독 감정적이다. 말투가 어딘가 익숙하다.',
    reveals: ['고요'] },

  { id: 31, chain: 'ALIBI', suspect: 'B', tag: 'redherring',
    keywords: ['밤안개 사건 당일'], requires: [],
    title: '표민준의 주장',
    body: '표민준은 사건 당일 자기 집에 있었다고 주장한다.',
    reveals: ['밤안개 집'] },
  { id: 32, chain: 'ALIBI', suspect: 'B', tag: 'redherring',
    keywords: ['밤안개 집', '밤안개 알리바이'], requires: [31],
    title: '거주지 정보',
    body: '해당 주소지 인근에는 CCTV가 거의 없어 알리바이를 확인하기 어렵다.',
    reveals: [] },
  { id: 33, chain: 'ALIBI', suspect: 'B', tag: 'redherring',
    keywords: ['밤안개 sns', '밤안개 업로드'], requires: [31],
    title: 'SNS 업로드',
    body: '표민준은 사건 당일 저녁 집에서 찍은 것으로 보이는 사진을 SNS에 올렸다.',
    reveals: ['사진 메타데이터'] },
  { id: 34, chain: 'ALIBI', suspect: 'B', tag: 'redherring',
    keywords: ['사진 메타데이터'], requires: [33],
    title: '메타데이터 확인',
    body: '사진의 촬영 시간이 업로드 시간과 며칠이나 차이가 난다.',
    reveals: ['재업로드 사진'] },
  { id: 35, chain: 'ALIBI', suspect: 'B', tag: 'redherring',
    keywords: ['재업로드 사진'], requires: [34],
    title: '거짓 알리바이',
    body: '표민준은 예전 사진을 재업로드해 알리바이를 조작했다. 사실은 그날 게임을 땡땡이치고 몰래 놀러 나갔던 것을 숨기려던 것뿐이었다.',
    reveals: [] },

  { id: 36, chain: 'HIDDEN', suspect: 'E', tag: 'lead',
    keywords: ['코스모스84 겨울정원'], requires: [],
    title: '오래된 게시글',
    body: '몇 년 전 다른 커뮤니티에서 코스모스84와 겨울정원이 나눈 대화를 발견한다.',
    reveals: [] },
  { id: 37, chain: 'HIDDEN', suspect: 'E', tag: 'support',
    keywords: ['겨울정원 날짜 확인'], requires: [36],
    title: '작성 시기',
    body: '지금의 채팅방이 만들어지기 훨씬 전부터 두 사람은 알던 사이였다.',
    reveals: ['겨울정원 과거 닉네임'] },
  { id: 38, chain: 'HIDDEN', suspect: 'E', tag: 'support',
    keywords: ['겨울정원 과거 닉네임'], requires: [37],
    title: '과거 계정',
    body: '두 사람이 서로 다른 닉네임으로 같은 팬 커뮤니티에서 활동한 흔적이 나온다.',
    reveals: [] },
  { id: 39, chain: 'HIDDEN', suspect: 'E', tag: 'redherring',
    keywords: ['겨울정원 댓글 패턴'], requires: [38],
    title: '표현 패턴',
    body: '둘만 아는 것 같은 특이한 표현을 반복해서 쓴다.',
    reveals: ['그 골목 얘기'] },
  { id: 40, chain: 'HIDDEN', suspect: 'E', tag: 'redherring',
    keywords: ['그 골목 얘기'], requires: [39],
    title: '표현의 의미',
    body: '알고 보니 그냥 같은 팬덤에서 쓰던 농담이었다. 다만 도경이 예전부터 "그 골목"(온새미로) 이야기를 알고 있었다는 사실은 확인된다.',
    reveals: [] },

  { id: 41, chain: 'F', suspect: 'F', tag: 'lead',
    keywords: ['고요'], requires: [],
    title: '검색 결과 거의 없음',
    body: '"고요"라는 닉네임으로는 이렇다 할 정보가 나오지 않는다. 지나치게 깨끗하다.',
    reveals: ['고요 백'] },
  { id: 42, chain: 'F', suspect: 'F', tag: 'lead',
    keywords: ['고요 백', '백고요'], requires: [41],
    title: '비슷한 옛 계정',
    body: '몇 년 전 만들어진 뒤 방치된 "백고요"라는 계정을 발견한다.',
    reveals: ['백고요'] },
  { id: 43, chain: 'F', suspect: 'F', tag: 'lead',
    keywords: ['백고요'], requires: [42],
    title: '옛 게시글의 댓글',
    body: '백고요 계정이 활동하던 시절, 한도경이 그 게시글에 댓글을 남긴 흔적이 있다.',
    reveals: [] },
  { id: 44, chain: 'F', suspect: 'F', tag: 'support',
    keywords: ['백고요 날짜 확인'], requires: [43],
    title: '시기 확인',
    body: '지금의 채팅방 멤버들을 만나기 한참 전부터, 한도경과 백준경은 이미 서로를 알고 있었다.',
    reveals: [] },
  { id: 45, chain: 'F', suspect: 'F', tag: 'lead',
    keywords: ['백고요 온새미로'], requires: [44],
    title: '공유된 기억',
    body: '두 사람 모두 "온새미로" 골목을 예전부터 알고 있었다는 정황이 겹친다.',
    reveals: ['결정적 단서'] },

  { id: 46, chain: 'FINAL', suspect: null, tag: 'decisive',
    keywords: ['코스모스84 온새미로'], requires: [9, 45],
    title: '실종자의 마지막 검색',
    body: '한도경은 실종 당일 저녁, "온새미로 골목"을 직접 검색했다. 모임 장소가 아니라 그 뒷골목으로 향했다는 뜻이다.',
    reveals: [] },
  { id: 47, chain: 'FINAL', suspect: 'C', tag: 'redherring',
    keywords: ['필름누아르 온새미로'], requires: [46],
    title: '또 다른 검색 기록',
    body: '필름누아르 역시 같은 골목을 검색했다. 그러나 이유는 단순히 "후기용 사진을 더 찍으러" 였을 뿐, 그날 그 시간에 그곳에 간 기록은 없다.',
    reveals: [] },
  { id: 48, chain: 'FINAL', suspect: 'F', tag: 'decisive',
    keywords: ['백준경 온새미로', '고요 온새미로'], requires: [45],
    title: '오래된 글 한 편',
    body: '백준경이 예전에 남긴, 온새미로 골목에 대한 원망 섞인 짧은 글이 발견된다. "언젠가 다 밝혀질 거야"라는 문장으로 끝난다.',
    reveals: [] },
  { id: 49, chain: 'FINAL', suspect: 'F', tag: 'decisive',
    keywords: ['사진 수정 시간 비교', '사진 수정 시간과 채팅 기록'], requires: [20, 48],
    title: '시간의 일치',
    body: '단체사진이 수정된 시각은, 한도경이 마지막으로 접속했던 시간 직후와 정확히 겹친다.',
    reveals: [] },
  { id: 50, chain: 'FINAL', suspect: 'F', tag: 'decisive',
    keywords: ['최종 결론', '모든 단서 연결'], requires: [46, 47, 48, 49],
    title: '연결된 하나의 이름',
    body: '한도경이 마지막으로 만나기로 한 사람, 사진에서 그를 지운 사람, 그를 온새미로 골목으로 이끈 사람 — 이 세 가지 질문의 답이 전부 한 사람으로 모인다: 백준경.',
    reveals: [] },
];

const TRUTH = {
  culprit: 'F',
  location: '온새미로',
  photoReason: '도경이 그날 그 장소에 없었던 것처럼 보이게 하려고',
  method: '평소처럼 존재감 없이 행동하며 의심을 피함',
};
